# Enables logging of Mongo mapping events
logging.level.org.springframework=INFO
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG

management.endpoints.access.default=read_only
spring.web.error.include-stacktrace=ALWAYS
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

#
# Verifier options
#
verifier.originalClientId=Verifier
verifier.clientIdPrefix=pre-registered
verifier.access-certificate.signing-algorithm=ES512
verifier.access-certificate.keystore=classpath:keystore.jks
verifier.access-certificate.keystore.type=jks
verifier.access-certificate.keystore.password=keystore
verifier.access-certificate.alias=access_certificate
verifier.access-certificate.password=access_certificate
verifier.publicUrl=http://localhost:${server.port}
verifier.requestJwt.embed=ByReference
verifier.requestJwt.requestUriMethod=Get
verifier.response.mode=DirectPostJwt
verifier.maxAge=PT6400M
verifier.presentations.cleanup.maxAge=P10D
verifier.authorizationRequestUri=haip-vp://
verifier.allowedRedirectUriSchemes=https

# clientMetadata parameters
verifier.clientMetadata.vpFormats.sdJwtVc.enabled=true
verifier.clientMetadata.vpFormats.sdJwtVc.sdJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.sdJwtVc.kbJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.msoMdoc.enabled=true

#
# Configuration parameters for validations applied by verifier
# to wallet presentations or in utilities api
#
verifier.validation.sdJwtVc.statusCheck.enabled=true

# transaction data
verifier.transactionData.hashAlgorithm=sha-256

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600

# Trust Validator Service Configuration
#verifier.trust.service-url=https://dev.trust-validator.eudiw.dev/trust

# Attestation Classifications
#verifier.attestation-classifications={"pid":{"vcts":["urn:eudi:pid:1"],"docTypes":["eu.europa.ec.eudi.pid.1"]},"qeaa":{"vcts":[],"docTypes":[]},"pubeaa":{"vcts":["urn:eudi:ehic:1"],"docTypes":[]},"eaa":[{"useCase":"mDL","vcts":[],"docTypes":["org.iso.18013.5.1.mDL"]},{"useCase":"learningCredential","vcts":["urn:eu.europa.ec.eudi:learning:credential:1"],"docTypes":[]}]}

# Proxy settings
#verifier.http.proxy.url=http://example.com
#verifier.http.proxy.username=test
#verifier.http.proxy.password=test

# SD-JWT-VC Validation configuration
verifier.validation.sdJwtVc.kbJwt.clock.skew=PT5S

verifier.validation.sdJwtVc.typeMetadata.policy=not-used
#verifier.validation.sdJwtVc.typeMetadata.policy.requiredFor=urn:eudi:pid:1

# SD-JWT VC Type Metadata resolution
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.ttl=PT1H
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.maxEntries=10
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.enabled=false
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.allowedAlgorithms=sha256,sha384,sha512
#verifier.validation.sdJwtVc.typeMetadata.resolution.vcts[0].vct=urn:eudi:pid:1
#verifier.validation.sdJwtVc.typeMetadata.resolution.vcts[0].url=https://dev.issuer-backend.eudiw.dev/type-metadata/urn:eudi:pid:1

